### ISSUE TITLE
backup-n-restore umbrella issue

### ISSUE THREAD

**Issue by sdminonne** [open-cluster-management/sre-tools#10]
This issue tracks 
- [ ] Modifying original syncset in new hub managed cluster namespace
- [ ] Test with placement rules
- [ ] Test with GRC
- [ ] Test with 10 managed clusters. Results should be reported for backup **and** restore
